### ISSUE TITLE
Readme requested

### ISSUE THREAD

**Issue by stof** [api-platform/api-pack#1]
You should add a readme explaining what this repo is about.

As the composer metadata use the `metapackage` type, this won't impact users as the source will never be downloaded. But it will help people looking at the repo

**Comment by allemas** [comment]
Here, some ressources to setup api platform:
- [The github project with example](https://github.com/api-platform/api-platform/tree/master/api)
- [The official documentation](https://api-platform.com/docs/core/getting-started)

I don't think, we can add readme to this repository. This repository is used by flex to setup the projects.

**Comment by greg0ire** [comment]
> I don't think, we can add readme to this repository. This repository is used by flex to setup the projects.

So what?

**Comment by mateuszsip** [comment]
also https://symfony.sh/ can display/link that `README` to give some insight people looking for new tools.

**Comment by sroze** [comment]
What would you like to see in this `README.md` file?

**Comment by greg0ire** [comment]
The bare minimum, for starters: http://www.writethedocs.org/guide/writing/beginners-guide-to-docs/#what-to-write

**Comment by lloy0076** [comment]
#11
