### ISSUE TITLE
 ApiPlatform\Core\Bridge\Elasticsearch

### ISSUE THREAD

**Issue by methodeprog** [api-platform/api-pack#19]
Hi !
I'm an API Pack user and atfer updated, i'm on ^1.2.
The issue is that some filter are not on the bundle.

use ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Filter\TermFilter;
Precisely Elasticsearch

How could i proceed as i us the api pack.

Thank fo all !

**Comment by alanpoulain** [comment]
Try to do `composer req api-platform/core:^2.4@beta` in your project.

**Comment by methodeprog** [comment]
@alanpoulain, 
i tried but get 
// Could not find package api-platform/core in a version matching 2.4@beta.
I move from "api-platform/api-pack": "^1.1" to "api-platform/api-pack": "^1.2"
Before i launch php composer.phar req api-platform/core and get
// Using version ^2.3 for api-platform/core
Perhaps i do something wrong

**Comment by antograssiot** [comment]
Given the error, you might have forgotten the `^` @methodeprog

**Comment by methodeprog** [comment]
Great thank for support, it work now with all dependencies, procedure change a little.
I put directly "api-platform/core": "^2.4@beta", in composer.json, then run php composer.phar update.
Happy day/afternoon , value team member !
