### ISSUE TITLE
Get rid of this pack

### ISSUE THREAD

**Issue by MLDMoritz** [api-platform/api-pack#21]
Hey,

using this pack will lead to frustrated users because the dependencies are not up to date.

I would recommend users to just copy the contents of the composer.json and put it in their own with adapted versions.

**Comment by soyuka** [comment]
Hi, what dependencies were an issue?

**Comment by teohhanhui** [comment]
> I would recommend users to just copy the contents of the composer.json and put it in their own with adapted versions.

You can use `composer unpack api` (Symfony Flex).

**Comment by dunglas** [comment]
I cannot reproduce:

```
$ symfony new test-pack
$ composer req api
$ composer show api-platform/core
> versions : * v2.5.0
```

It looks ok to me, or am I missing something?

**Comment by MLDMoritz** [comment]
Hey,

seems I ended up on version 2.4.something while reading docs for 2.5...
