### ISSUE TITLE
composer req api fails with symfony/website-skeleton fresh install

### ISSUE THREAD

**Issue by GregoireHebert** [api-platform/api-pack#26]
**API Platform version(s) affected**: 2.5.*

**Description**  
It's not possible anymore to install API Platform from Symfony website skeleton 5.* with api-pack

**How to reproduce**  
```
composer create-project symfony/website-skeleton
cd website-skeleton
composer req api # fails
```

**Work Around**  
```
composer require phpdocumentor/reflection-docblock ^4.0
composer req api
composer unpack api-platform/api-pack
composer require phpdocumentor/reflection-docblock ^5.0
```

**Solution**  
`"phpdocumentor/reflection-docblock": "^3.0 || ^4.0 || ^5.0",`

**Comment by dunglas** [comment]
Fixed by #27 and released in v1.2.2.
