### ISSUE TITLE
Create a tag

### ISSUE THREAD

**Issue by fabpot** [api-platform/api-pack#3]
You should create a tag to ease installation (see symfony/recipes#140).

**Comment by stof** [comment]
Note that the requirement on `api-platform/core` must be changed first, because the `2.1.x-dev` constraint forbids using stable releases even after 2.1 is released. It should use a range instead

**Comment by mappedinn** [comment]
:+1:

**Comment by mappedinn** [comment]
@dunglas any updates for the tag?

Thanks...

**Comment by meyerbaptiste** [comment]
Hi, @dunglas is on vacation at the other end of the world until the 21st so we will have to wait a little!

BTW @mappedinn, meanwhile, you can run `composer req api-platform/api-pack:^2.1@dev api-platform/core:^2.1@dev` to install API Platform in your Symfony Flex application.

**Comment by dunglas** [comment]
We need to release 2.1 before I can tag this pack.

**Comment by mappedinn** [comment]
@meyerbaptiste thank you for the tip...

It worked without having to set the `minimum-stability` to `dev`.

Any way, I will be waiting for the tag.

best,

**Comment by Engerim** [comment]
@dunglas I think now a stable release is possible. Because at the moment the pack does not allow to  upgrade to stable

**Comment by dunglas** [comment]
The tag has been created.
