### ISSUE TITLE
Unused vendor?

### ISSUE THREAD

**Issue by Saphyel** [api-platform/api-pack#7]
Why is required `symfony/twig-bundle`?

Would be possible that someone review if every vendor is really required?

**Comment by soyuka** [comment]
Yes it is required by swagger.

**Comment by Saphyel** [comment]
@soyuka then I think should be a required by swagger

**Comment by dunglas** [comment]
It is required to display the automatically generated documentation. If you want to get rid of this dep, you can use the new `unpack` feature of Flex and cherry-pick your deps.
